name: Build Multiarch Container Images
# inspired by https://docs.docker.com/build/ci/github-actions/examples/
on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
   branches: [ main ]

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    name: multi-arch image build
    env:
      PLATFORMS: linux/amd64,linux/arm64
      REGISTRY_GH: ghcr.io

    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: "go"
          token: ${{ secrets.RP_PAT }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY_GH }}/${{ github.repository }}
          tags: |
            type=schedule,pattern=nightly,enable=true,priority=1000
            type=ref,event=branch,enable=true,priority=600
            type=ref,event=tag,enable=true,priority=600
            type=ref,event=pr,prefix=pr-,enable=true,priority=600
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }},priority=600

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_GH }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images to registries
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
